from fastapi.responses import HTMLResponse


def dashboard() -> HTMLResponse:
    return HTMLResponse("""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sentinel · IOC Intelligence</title><meta name="description" content="Analyze indicators of compromise with explainable threat intelligence.">
<style>
:root{color-scheme:dark;--bg:#07100e;--panel:#0d1916;--line:#20352f;--ink:#edf8f2;--muted:#91aaa0;--lime:#71f6b5;--red:#ff6b78}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 0,#123c30 0,transparent 32rem),var(--bg);color:var(--ink);font:16px/1.55 Inter,ui-sans-serif,system-ui,sans-serif;min-height:100vh}.shell{width:min(1080px,calc(100% - 2rem));margin:auto}header{display:flex;justify-content:space-between;align-items:center;padding:1.4rem 0;border-bottom:1px solid var(--line)}.brand{font-size:1.25rem;font-weight:800;letter-spacing:.08em}.brand span,.eyebrow{color:var(--lime)}header a{color:var(--muted);text-decoration:none}main{padding:4rem 0}.eyebrow{font-size:.78rem;font-weight:800;letter-spacing:.16em}h1{font-size:clamp(2.8rem,8vw,6.5rem);line-height:.92;margin:.6rem 0 1.4rem;letter-spacing:-.065em;max-width:850px}h1 span{color:var(--lime)}.lead{max-width:700px;color:var(--muted);font-size:1.1rem}.analyzer{margin:3rem 0 1.5rem;padding:1rem;background:rgba(13,25,22,.92);border:1px solid var(--line);border-radius:18px;box-shadow:0 24px 70px #0007}.form{display:flex;gap:.7rem}input{width:100%;background:#08120f;border:1px solid #2a443b;color:var(--ink);border-radius:12px;padding:1rem;font:inherit;outline:none}input:focus{border-color:var(--lime);box-shadow:0 0 0 3px #71f6b522}button{border:0;border-radius:12px;background:var(--lime);color:#052016;font-weight:800;padding:0 1.5rem;cursor:pointer}button:disabled{opacity:.5;cursor:wait}.examples{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.8rem}.examples button{padding:.45rem .7rem;background:#172822;color:var(--muted);font-size:.78rem}.status{margin-top:1rem;color:var(--muted);min-height:1.6rem}.result{display:none;margin-top:1.5rem}.score-row{display:grid;grid-template-columns:180px 1fr;gap:1.4rem;align-items:center}.gauge{aspect-ratio:1;border-radius:50%;display:grid;place-items:center;background:conic-gradient(var(--lime) calc(var(--score)*1%),#1c3029 0);position:relative}.gauge:after{content:"";position:absolute;inset:14px;background:var(--panel);border-radius:50%}.gauge strong{font-size:2.5rem;z-index:1}.verdict{font-size:2.3rem;margin:0}.meta{color:var(--muted)}.reasons,.providers{display:grid;gap:.7rem;margin-top:1.4rem}.reason,.provider{background:#0a1512;border:1px solid var(--line);padding:.9rem 1rem;border-radius:10px}.provider{display:flex;justify-content:space-between;gap:1rem}.provider small{color:var(--muted)}.error{color:var(--red)}footer{padding:2rem 0 3rem;color:var(--muted);display:flex;gap:1rem;justify-content:space-between;border-top:1px solid var(--line)}footer a{color:var(--lime)}@media(max-width:650px){main{padding:2.5rem 0}.form{flex-direction:column}button{padding:1rem}.score-row{grid-template-columns:120px 1fr}.verdict{font-size:1.6rem}}
</style></head><body><div class="shell"><header><div class="brand">SENTINEL<span>.</span></div><a href="/docs">API docs ↗</a></header><main><p class="eyebrow">DEFENSIVE THREAT INTELLIGENCE</p><h1>Investigate indicators.<br><span>Understand the risk.</span></h1><p class="lead">Enter an IP address, domain, URL, file hash, or CVE. Sentinel checks relevant intelligence sources and returns one explainable risk report.</p><section class="analyzer"><div class="form"><input id="ioc" aria-label="Indicator of compromise" placeholder="Try CVE-2021-44228 or example.com" autocomplete="off"><button id="analyze">Analyze</button></div><div class="examples"><button data-ioc="CVE-2021-44228">CVE example</button><button data-ioc="8.8.8.8">IP example</button><button data-ioc="example.com">Domain example</button></div><div id="status" class="status" aria-live="polite"></div><div id="result" class="result"><div class="score-row"><div id="gauge" class="gauge"><strong id="score">0</strong></div><div><p class="eyebrow">THREAT ASSESSMENT</p><h2 id="verdict" class="verdict"></h2><div id="meta" class="meta"></div></div></div><div id="reasons" class="reasons"></div><div id="providers" class="providers"></div></div></section></main><footer><span>Built by Yousef Elshaer</span><a href="https://github.com/Yousef-elshaer/sentinel">View source ↗</a></footer></div><script>
const input=document.querySelector('#ioc'),button=document.querySelector('#analyze'),status=document.querySelector('#status'),result=document.querySelector('#result');document.querySelectorAll('[data-ioc]').forEach(x=>x.onclick=()=>{input.value=x.dataset.ioc;run()});button.onclick=run;input.onkeydown=e=>{if(e.key==='Enter')run()};async function run(){const ioc=input.value.trim();if(!ioc)return;button.disabled=true;status.className='status';status.textContent='Querying intelligence providers…';result.style.display='none';try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ioc})});const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'Analysis failed');document.querySelector('#score').textContent=data.risk_score;document.querySelector('#gauge').style.setProperty('--score',data.risk_score);document.querySelector('#verdict').textContent=data.verdict;document.querySelector('#meta').textContent=`${data.ioc} · ${data.ioc_type.toUpperCase()}${data.cached?' · cached':''}`;document.querySelector('#reasons').innerHTML=data.risk_explanations.map(x=>`<div class="reason">${escapeHtml(x)}</div>`).join('');document.querySelector('#providers').innerHTML=data.provider_results.map(x=>`<div class="provider"><strong>${escapeHtml(x.provider)}</strong><small>${escapeHtml(x.status.replace('_',' '))}${x.confidence!=null?' · '+x.confidence+'% confidence':''}</small></div>`).join('');status.textContent='';result.style.display='block'}catch(e){status.className='status error';status.textContent=e.message}finally{button.disabled=false}}function escapeHtml(x){const d=document.createElement('div');d.textContent=String(x);return d.innerHTML}
</script></body></html>""")
